### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by BrycensRanch** [BrycensRanch/AuthIsForMe#56]
Upon trying to use Node 20, node-canvas on Linux fails to install and building it with node-gyp fails, regardless ofthe required dependencies for building being installed. Tested on Ubuntu 22.04.3 LTS x86_64. Requires more testing.

**Comment by Romvnly-Gaming** [comment]
How dare you assign me boy

**Comment by BrycensRanch** [comment]
😠😠 get to coding boy

**Comment by BrycensRanch** [comment]
we should only be using lts node
